# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright (c) 2020-2025 MariaDB Corporation Ab

"""
Type stubs for the ``mariadb_c._mariadb`` C extension.

The compiled extension exposes two types (``connection`` and ``cursor``) plus a
couple of module-level constants. These stubs describe their public surface so
that the pure-Python wrapper classes in ``mariadb_c.connections`` /
``mariadb_c.cursors`` (which subclass these C types) type-check correctly.

Signatures are derived from the PyMethodDef / PyGetSetDef / PyMemberDef tables in
``mariadb_connection.c`` and ``mariadb_cursor.c``. Genuinely dynamic values
returned by libmariadb are typed ``Any``.
"""

from typing import Any, List, Optional

mariadbapi_version: str
_have_asan: bool


class connection:
    # --- members (PyMemberDef) ---
    dsn: Any
    _closed: bool
    _converter: Any
    _tls: bool

    # --- getset (PyGetSetDef) ---
    auto_reconnect: bool
    @property
    def connection_id(self) -> int: ...
    @property
    def warnings(self) -> int: ...

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    # --- methods (PyMethodDef) ---
    # close/connect/change_user/reconnect/reset/dump_debug_info are returned as
    # Any because the async wrapper (AsyncConnection) overrides them with
    # coroutine versions; Any keeps both the sync (-> None) and async
    # (-> Coroutine) overrides compatible with this shared C base.
    def close(self) -> Any: ...
    def connect(self, *args: Any, **kwargs: Any) -> Any: ...
    def _sync_ping(self) -> None: ...
    def change_user(self, *args: Any, **kwargs: Any) -> Any: ...
    def reconnect(self) -> Any: ...
    def reset(self) -> Any: ...
    def escape_string(self, string: str) -> str: ...
    def dump_debug_info(self) -> Any: ...
    def _mariadb_get_info(self, option: int) -> Any: ...
    def _get_socket(self) -> int: ...
    def get_socket(self) -> int: ...
    def get_timeout_value(self) -> int: ...
    def _init_fields_only(self) -> None: ...
    def set_nonblock_option(self) -> None: ...
    def _check_socket_ready(self, *args: Any) -> int: ...
    def _close_stmt_capsule(self, capsule: Any) -> None: ...
    def _neutralize_stmt_capsule(self, capsule: Any) -> None: ...

    # Non-blocking start/cont pairs (MARIADB_ASYNC_OP): *_start kicks off the
    # operation, *_cont resumes it given the observed wait-status. Each returns
    # an int wait-status while the op is still pending, or None once complete.
    def _async_real_query_start(self, *args: Any) -> Optional[int]: ...
    def _async_real_query_cont(self, status: int) -> Optional[int]: ...
    def _async_ping_start(self) -> Optional[int]: ...
    def _async_ping_cont(self, status: int) -> Optional[int]: ...
    def _async_close_start(self) -> Optional[int]: ...
    def _async_close_cont(self, status: int) -> Optional[int]: ...
    def _async_change_user_start(self, *args: Any) -> Optional[int]: ...
    def _async_change_user_cont(self, status: int) -> Optional[int]: ...
    def _async_reset_start(self) -> Optional[int]: ...
    def _async_reset_cont(self, status: int) -> Optional[int]: ...
    def _async_dump_debug_info_start(self) -> Optional[int]: ...
    def _async_dump_debug_info_cont(self, status: int) -> Optional[int]: ...


class cursor:
    # --- members (PyMemberDef) ---
    statement: Optional[str]
    _reprepare: int
    _text: bool
    _resulttype: int
    paramcount: int
    _data: Any
    _cursor_type: int
    buffered: bool
    arraysize: int
    field_count: int
    affected_rows: int
    _rownumber: int
    insert_id: int

    # --- getset (PyGetSetDef) ---
    @property
    def description(self) -> Optional[Any]: ...
    @property
    def metadata(self) -> Optional[Any]: ...
    @property
    def rowcount(self) -> int: ...
    @property
    def warnings(self) -> int: ...
    @property
    def closed(self) -> bool: ...
    @property
    def rownumber(self) -> Optional[int]: ...

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    # --- methods (PyMethodDef) ---
    # close is Any so the async wrapper (AsyncCursor) can override it with a
    # coroutine version (see connection.close note).
    def close(self) -> Any: ...
    def fetchone(self) -> Optional[Any]: ...
    def fetchrows(self, size: int) -> List[Any]: ...
    def next(self) -> Optional[Any]: ...
    def _nextset(self) -> Optional[bool]: ...
    def _reset(self) -> None: ...
    def _seek(self, pos: int) -> None: ...
    def _initresult(self) -> None: ...
    def _clear_result(self) -> None: ...
    def _set_field_count_from_connection(self) -> None: ...

    # Prepared-statement handle plumbing (used by StmtReuseMixin).
    def _detach_stmt(self) -> Optional[Any]: ...
    def _attach_stmt(self, capsule: Any) -> None: ...
    def _set_statement(self, statement: str, paramcount: int) -> None: ...
    def _set_text_statement(self, statement: Any) -> None: ...

    # Execution.
    def _sync_readresponse(self) -> None: ...
    def _sync_execute_text(self, *args: Any) -> None: ...
    def _execute_binary(self) -> None: ...
    def _execute_bulk(self) -> None: ...
    def _prepare_bulk_only(self) -> None: ...
    def _prepare_stmt_only(self) -> None: ...
    def _finalize_bulk_result(self) -> None: ...

    # Non-blocking start/cont pairs (see connection note). prepare/execute return
    # an int wait-status while pending or None when complete. The fetch and
    # next-result pairs additionally yield row data / a bool on completion, so
    # they stay Any (int wait-status while pending; row|None or bool when done).
    def _async_fetch_row_start(self) -> Any: ...
    def _async_fetch_row_cont(self, status: int) -> Any: ...
    def _async_stmt_prepare_start(self) -> Optional[int]: ...
    def _async_stmt_prepare_cont(self, status: int) -> Optional[int]: ...
    def _async_stmt_execute_start(self) -> Optional[int]: ...
    def _async_stmt_execute_cont(self, status: int) -> Optional[int]: ...
    def _async_stmt_fetch_start(self) -> Any: ...
    def _async_stmt_fetch_cont(self, status: int) -> Any: ...
    def _async_next_result_start(self) -> Any: ...
    def _async_next_result_cont(self, status: int) -> Any: ...
