# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright (c) 2020-2025 MariaDB Corporation Ab

"""
Structural (Protocol) types for the optional connection-pool classes.

``mariadb_pool`` is an *optional* dependency, so the connector cannot import its
classes at type-check time when it isn't installed (the names would resolve to
``Any``, which can't be used in type expressions). These Protocols live in
``mariadb_shared`` — a hard dependency that is *always* importable — and mirror
the public surface of the ``mariadb_pool`` classes, so pool annotations type-check
cleanly whether or not ``mariadb_pool`` is installed. The real classes satisfy
these Protocols structurally (their concrete connection return types are subtypes
of the shared *ConnectionCommon bases used here).
"""
from __future__ import annotations

from contextlib import AbstractAsyncContextManager, AbstractContextManager
from typing import Any, Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    from mariadb_shared.sync_connection_common import SyncConnectionCommon
    from mariadb_shared.async_connection_common import AsyncConnectionCommon


class ConnectionPoolWrapper(Protocol):
    """Structural type for ``mariadb_pool.ConnectionPoolWrapper``."""
    def _check_conn_args(self, kwargs: dict[str, Any]) -> None: ...
    def get_connection(self) -> SyncConnectionCommon[Any]: ...
    def add_connection(self, connection: SyncConnectionCommon[Any] | None = None) -> None: ...
    def set_config(self, **kwargs: Any) -> None: ...
    def close(self) -> None: ...
    pool_name: str | None
    def __enter__(self) -> ConnectionPoolWrapper: ...
    def __exit__(self, *exc: object) -> None: ...
    @property
    def connection_count(self) -> int: ...
    @property
    def pool_reset_connection(self) -> bool: ...
    @property
    def pool_size(self) -> int: ...
    @property
    def max_size(self) -> int: ...


class ConnectionPool(Protocol):
    """Structural type for ``mariadb_pool.ConnectionPool`` (``create_pool`` result)."""
    # The pool's PoolConfig; its class lives in mariadb_pool, which this
    # package cannot import, hence Any.
    config: Any
    def acquire(self, timeout: float | None = None) -> SyncConnectionCommon[Any]: ...
    def release(self, pool_conn: Any) -> None: ...
    def connection(self, timeout: float | None = None) -> AbstractContextManager[SyncConnectionCommon[Any]]: ...
    def close(self) -> None: ...


class AsyncConnectionPool(Protocol):
    """Structural type for ``mariadb_pool.AsyncConnectionPool`` (``create_async_pool`` result)."""
    # The pool's PoolConfig; its class lives in mariadb_pool, which this
    # package cannot import, hence Any.
    config: Any
    async def open(self) -> None: ...
    async def acquire(self, timeout: float | None = None) -> AsyncConnectionCommon[Any]: ...
    async def release(self, pool_conn: Any) -> None: ...
    def connection(self, timeout: float | None = None) -> AbstractAsyncContextManager[AsyncConnectionCommon[Any]]: ...
    async def close(self) -> None: ...
